name:                solitaire
version:             0.1.0.0
github:              "quasarbright/solitaire"
license:             BSD3
author:              "Mike Delmonaco"
maintainer:          "mdelmonacochs@gmail.com"
copyright:           "Mike Delmonaco"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/quasarbright/solitaire#readme>

dependencies:
- base >= 4.7 && < 5
- lens
- mtl
- boxes
- parsec
- repline
- random-shuffle

library:
  source-dirs: src

executables:
  solitaire-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - solitaire

tests:
  solitaire-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - solitaire
